development:
  title  : Joruri Mail
  uri    : http://192.168.0.2/
  proxy  :
  map_key:
  mail_domain: 192.168.0.4

test:
  title  :
  uri    :
  proxy  :
  map_key:
  mail_domain:

production:
  title  :
  uri    :
  proxy  :
  map_key:
  mail_domain:

